Repository openshift/tektoncd-triggers, pull requests merged in 2020-09, with the labels that each got.

#261 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
  openshift/release/tektoncd-triggers-nightly.yaml
Labels: kind/sync-fork-to-upstream

#262 Add release.yaml file for v0.8.1
  openshift/release/tektoncd-triggers-v0.8.1.yaml
Labels: approved, lgtm

#276 Add midstream release notes for triggers
  openshift/release/release-notes.md
Labels: approved, lgtm

#280 Triggers CI
  ci
Labels: approved
