Repository openshift/tektoncd-triggers, pull requests merged in 2020-03, with the labels that each got.

#81 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
  openshift/release/tektoncd-triggers-nightly.yaml
Labels: kind/sync-fork-to-upstream, size/XL

#82 Removing myself from approvers/reviewers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#88 Triggering CI on branch release-v0.3.1
  ci
Labels: approved, size/XS

#100 Use tag based url
  openshift/pipeline-latest-release.sh
Labels: approved, lgtm

#101 Remove extra space
  openshift/resolve-yamls.sh
Labels: approved, lgtm
